### ISSUE TITLE
Hello please read

### ISSUE THREAD

**Issue by charyung** [Magichanics/WorksCitedGenerator#2]
I hope you see this.

You left our only mutual server so I couldn't message you or send you a friend request. That's why I'm here.

I give your files a read, and thought it's pretty good overall, though there's a few small things.

1. If you're intending to share this to let other people use, consider adding a Readme for installation/usage instructions.

2. Maybe you're just doing this for testing purposes, but in `historyextract.py`, it's not a good idea to hardcode things like `"\\AppData\\Local\\Google\\Chrome\\User Data\\Default"` since someone else using it might not be using Chrome.

3. In `workscitedgenerator.py`, I see `get_date_attribute()`. However, that's not necessary since `getattr` (a default Python function; you can read about it [here](https://docs.python.org/3.7/library/functions.html#getattr)) exists. If you didn't already know, a good rule of thumb to remember is [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). Something repetitive like that function usually has some kind of work around.

Good luck on your university acceptances!

- @Ser Chairzard#3463

**Comment by Magichanics** [comment]
Thank you. I will apply these changes right now.
